name: metrics_center

dependencies:
  args: any
  crypto: any
  gcloud: any
  googleapis: any
  googleapis_auth: any
  github: ^6.0.0

dev_dependencies:
  test: any
  pedantic: ^1.8.0

environment:
  sdk: ">=2.2.2 <3.0.0"
